### ISSUE TITLE
[Yarn] Yarn install throws an error 

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#1216]
We've seen two errors with `yarn install` when Yarn is at version 0.17. 

* Using `0.16.1 fixes the issues.
* Even though there's an error, the install might still be successful (lets confirm this)

Error 1: npm-workerjs

```
error An unexpected error occurred: "ENOENT: no such file or directory, 
lstat '/Users/santosh.v04/Library/Caches/Yarn/npm-workerjs-0.1.1-6c53f106c5664d4691c241ab2f43c5afe4d74fa8'".
```

Error 2: roadrunner.json
[issue](https://github.com/yarnpkg/yarn/issues/1724)

```
/home/ubuntu/.yarn/bin/yarn.js:47
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/home/ubuntu/.cache/yarn/.roadrunner.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /home/ubuntu/.yarn/node_modules/roadrunner/index.js:25:6
    at /home/ubuntu/.yarn/node_modules/roadrunner/index.js:12:12
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/home/ubuntu/.yarn/node_modules/signal-exit/index.js:140:35)
    at process.exit (internal/process.js:146:15)
    at Command.<anonymous> (/home/ubuntu/.yarn/node_modules/commander/index.js:825:13)
> Yarn was installed, but doesn't seem to be working :(.

```

**Comment by jasonLaster** [comment]
@juliandescottes here is the `roadrunner` bug. I'm surprised that you were seeing it with `0.16.1`. Lets see if we can come up with a fix soon. Happy to help later.

**Comment by jasonLaster** [comment]
closing as Yarn is not being flakey on CI and others aren't reporting this. We can re-open if they do.

#1235

**Comment by stellargo** [comment]
```
Users-MacBook-Pro:debugger.html User$ yarn start
yarn start v1.0.1
$ node bin/dev-server
module.js:474
    throw err;
    ^

Error: Cannot find module 'devtools-launchpad/index'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/User/debugger.html/bin/dev-server.js:4:17)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
error Command failed with exit code 1.
```
Getting the above error when starting yarn.
node version: 7.0.0
nvm version: 0.32.1

**Comment by robwierzbowski** [comment]
@jasonLaster I've been experiencing your error 1 often lately. Did you find a fix?

**Comment by 10ko** [comment]
Hello there, I am getting this error after a fresh `yarn install`:
```
✔ ~/code/debugger [master|✚ 1]
12:16 $ yarn start
yarn run v1.17.3
$ node bin/dev-server
Listening for WS on localhost:8116, all traffic is proxied to localhost:6080
Protocol messages can be logged by enabling `logging.firefoxProxy` `in /configs/local.json`
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'devtools-mc-assets'
Require stack:
- /Users/emanuele/code/debugger/node_modules/devtools-launchpad/src/development-server.js
- /Users/emanuele/code/debugger/node_modules/devtools-launchpad/index.js
- /Users/emanuele/code/debugger/bin/dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at Object.startDevServer (/Users/emanuele/code/debugger/node_modules/devtools-launchpad/src/development-server.js:187:26)
    at Object.<anonymous> (/Users/emanuele/code/debugger/bin/dev-server.js:15:23)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/emanuele/code/debugger/node_modules/devtools-launchpad/src/development-server.js',
    '/Users/emanuele/code/debugger/node_modules/devtools-launchpad/index.js',
    '/Users/emanuele/code/debugger/bin/dev-server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My environment:
```
yarn: 1.17.3
node: v12.4.0
npm: 6.9.0
```

Should I open a new issue or do you have any pointer?
Thanks a lot.
E

**Comment by sujaykumardey** [comment]
cd debugger,
after checkout release-120 branch
then yarn install,
yarn start
start localhost:8000,
![Screenshot from 2020-05-27 16-19-37](https://user-images.githubusercontent.com/31136549/83011076-efcba400-a036-11ea-9587-de90ba545765.png)
