### ISSUE TITLE
yarn run firefox fails in Fedora 24

### ISSUE THREAD

**Issue by andreicristianpetcu** [devtools-html/debugger.html#1422]
`yarn run firefox` used to run a few weeks ago in Fedora 24 but now it fails.
Here is the stack trace

```bash
$yarn run firefox                                                                                                                                                 yarn run v0.17.10
$ node bin/firefox-driver --start 
/home/andrei/Dev/debugger.html/debugger.html/bin/firefox-driver.js:31
  let binary = new firefox.Binary();
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$node --version                                                                                                                                                   v4.6.1
```

It also fails with ndenv's nodejs.
```bash
$ndenv local v6.9.2
$node --version 
v6.9.2
$yarn run firefox                                                                                                                                                 yarn run v0.17.10
$ node bin/firefox-driver --start 
/home/andrei/Dev/debugger.html/node_modules/selenium-webdriver/lib/promise.js:2517
        throw error;
        ^

Error: Server terminated early with status 1
    at Error (native)
    at earlyTermination.catch.e (/home/andrei/Dev/debugger.html/node_modules/selenium-webdriver/remote/index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/andrei/Dev/debugger.html/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/home/andrei/Dev/debugger.html/node_modules/selenium-webdriver/firefox/index.js:640:55)
    at createDriver (/home/andrei/Dev/debugger.html/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/home/andrei/Dev/debugger.html/node_modules/selenium-webdriver/index.js:642:16)
    at start (/home/andrei/Dev/debugger.html/bin/firefox-driver.js:59:6)
    at Object.<anonymous> (/home/andrei/Dev/debugger.html/bin/firefox-driver.js:65:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by andreicristianpetcu** [comment]
Two small mentiones:
 - I use Firefox Nightly;
 - [It works manually](https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md#starting-firefox);

**Comment by jasonLaster** [comment]
Strange, this looks like a gecko driver bug. 

The create session is the tell for me

Perhaps file there as well

**Comment by jasonLaster** [comment]
@tromey do you run fedora 24? Would you mind [trying](https://github.com/devtools-html/debugger.html/blob/master/docs/getting-setup.md#step-3-open-firefox) this?

**Comment by tromey** [comment]
First I got:

```
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
```

Doesn't seem to be fatal.

Other than this it all worked for me.  I had to uninstall the Fedora `node` and instead install the `nodejs` package from the nodesource repository.

**Comment by andreicristianpetcu** [comment]
@tromey It still does not work for me. I fetched the latest sources from debugger.html, I have nodejs package installed and not node. I also get the warning you are mentioning while running yarn install.

**Comment by jasonLaster** [comment]
@andreicristianpetcu I know this is a big ask, but mind re-installing node v7 from nodesource?

**Comment by jasonLaster** [comment]
closing this now as this is likely a node issue. Lets re-open it if something new comes in

**Comment by andreicristianpetcu** [comment]
I installed latest node with ndenv. I have v7.3.0 and it still failed. It's ok to close it.

**Comment by jasonLaster** [comment]
hmm, @andreicristianpetcu weird. mind trying this for node 7.x- https://github.com/nodesource/distributions#installation-instructions

Also, perhaps try getting node 7.0. maybe 7.3 is broken :/

**Comment by jasonLaster** [comment]
closing, but lets keep talking here if you find something.

**Comment by andreicristianpetcu** [comment]
To be honest, I have a good workaround and I do not have much interest in troubleshooting this. If it bugs other people then it might be important but for now it is not.
