### ISSUE TITLE
Error: Cannot find module 'devtools-local-toolbox/index'

### ISSUE THREAD

**Issue by arthur801031** [devtools-html/debugger.html#1450]
I just switched to the master branch and ran `git fetch upstream` and `git rebase upstream/master`. When I ran `yarn start`, I got the following error:
```
yarn start v0.16.1
$ node bin/dev-server 
module.js:471
    throw err;
    ^

Error: Cannot find module 'devtools-local-toolbox/index'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/i-chun/Documents/debugger.html/bin/dev-server.js:4:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
error Command failed with exit code 1.
```

I tried `yarn upgrade` and `yarn install`, but they didn't work. Please help. Thank you!

**Comment by wldcordeiro** [comment]
I just ran into this as well you need to `rm -rf packages/` as for whatever reason the rebase doesn't remove those folders. It might also help to `rm -rf node_modules/`

**Comment by arthur801031** [comment]
@wldcordeiro Thank you so much! It worked! I ran
```
rm -rf packages/
rm -rf node_modules/
yarn upgrade
```
