### ISSUE TITLE
Problems installing mochitests

### ISSUE THREAD

**Issue by arthur801031** [devtools-html/debugger.html#1696]
I've encountered two problems while following this [guide]( https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md). Please help. Thank you!! :)

1. When I ran `brew install autoconf213 && brew unlink autoconf`, I got this error message:
```
Error: No available formula with the name "homebrew/core/autoconf@213" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

2. When I ran `./bin/prepare-mochitests-dev`, I got this error message:
```
starting: webpack
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
 0:00.33 /usr/bin/make -f client.mk -s configure
 0:01.32 cd /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend
 0:01.33 /Users/i-chun/Documents/debugger.html/firefox/configure
 0:01.57 Creating Python environment
 0:01.80 New python executable in /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/bin/python2.7
 0:01.80 Not overwriting existing python script /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/bin/python (you must use /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/bin/python2.7)
 0:01.80 Installing setuptools, pip, wheel...
 0:01.80   Complete output from command /Users/i-chun/Docume...ualenv/bin/python2.7 - setuptools pip wheel:
 0:01.80   Traceback (most recent call last):
 0:01.80   File "<stdin>", line 4, in <module>
 0:01.80   File "/Users/i-chun/anaconda/lib/python2.7/tempfile.py", line 32, in <module>
 0:01.80     import io as _io
 0:01.80   File "/Users/i-chun/anaconda/lib/python2.7/io.py", line 51, in <module>
 0:01.80     import _io
 0:01.80 ImportError: dlopen(/Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
 0:01.81   Referenced from: /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/lib/python2.7/lib-dynload/_io.so
 0:01.81   Expected in: flat namespace
 0:01.81  in /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/lib/python2.7/lib-dynload/_io.so
 0:01.81 ----------------------------------------
 0:01.81 ...Installing setuptools, pip, wheel...done.
 0:01.81 Traceback (most recent call last):
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 2325, in <module>
 0:01.81     main()
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 711, in main
 0:01.81     symlink=options.symlink and hasattr(os, 'symlink')) # MOZ: Make sure we don't use symlink when we don't have it
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 944, in create_environment
 0:01.81     download=download,
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 900, in install_wheel
 0:01.81     call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 795, in call_subprocess
 0:01.81     % (cmd_desc, proc.returncode))
 0:01.81 OSError: Command /Users/i-chun/Docume...ualenv/bin/python2.7 - setuptools pip wheel failed with error code 1
 0:01.81 Traceback (most recent call last):
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/configure.py", line 124, in <module>
 0:01.81     sys.exit(main(sys.argv))
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/configure.py", line 29, in main
 0:01.81     sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 334, in run
 0:01.81     self.include_file(path)
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 325, in include_file
 0:01.81     exec_(code, self)
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/util.py", line 59, in exec_
 0:01.81     exec(object, globals, locals)
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/moz.configure", line 7, in <module>
 0:01.81     include('build/moz.configure/init.configure')
 0:01.81   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 630, in include_impl
 0:01.81     self.include_file(what)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 325, in include_file
 0:01.82     exec_(code, self)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/util.py", line 59, in exec_
 0:01.82     exec(object, globals, locals)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/build/moz.configure/init.configure", line 145, in <module>
 0:01.82     @imports('distutils.sysconfig')
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 613, in decorator
 0:01.82     depends = DependsFunction(self, func, dependencies, when=when)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 69, in __init__
 0:01.82     sandbox._value_for(self)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 409, in _value_for
 0:01.82     return self._value_for_depends(obj, need_help_dependency)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/util.py", line 925, in method_call
 0:01.82     cache[args] = self.func(instance, *args)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 419, in _value_for_depends
 0:01.82     return obj.result
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/util.py", line 943, in __get__
 0:01.82     setattr(instance, name, self.func(instance))
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 90, in result
 0:01.82     return self.func(*resolved_args)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 938, in wrapped
 0:01.82     return new_func(*args, **kwargs)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/build/moz.configure/init.configure", line 192, in virtualenv_python
 0:01.82     manager.build(python)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/virtualenv.py", line 439, in build
 0:01.82     self.create(python)
 0:01.82   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/virtualenv.py", line 203, in create
 0:01.82     'Failed to create virtualenv: %s' % self.virtualenv_root)
 0:01.82 Exception: Failed to create virtualenv: /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv
 0:01.82 *** Fix above errors and then restart with               "/Applications/Xcode.app/Contents/Developer/usr/bin/make -f client.mk build"
 0:01.82 make: *** [configure] Error 1
```

**Comment by clarkbw** [comment]
I think I saw that `autoconf@213` was recently removed from homebrew

**Comment by clarkbw** [comment]
Try: `brew install autoconf@2.13`

**Comment by jasonLaster** [comment]
updated the docs: https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md

**Comment by arthur801031** [comment]
Thanks @clarkbw  @jasonLaster `brew install autoconf@2.13` works, but I'm getting this error:
```
I-Chuns-MacBook-2:debugger.html i-chun$ brew install mercurial
Warning: mercurial-4.0.2 already installed
I-Chuns-MacBook-2:debugger.html i-chun$ brew install autoconf@2.13 && brew unlink autoconf
Warning: autoconf@2.13-2.13 already installed
Unlinking /usr/local/Cellar/autoconf/2.69... 0 symlinks removed
I-Chuns-MacBook-2:debugger.html i-chun$ ./bin/prepare-mochitests-dev
There are local changes to Firefox which will be overwritten. Are you sure? [Y/n] Y
reverting devtools/client/debugger/new/test/mochitest/.eslintrc
reverting devtools/client/debugger/new/test/mochitest/browser.ini
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-breaking-from-console.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-breaking.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-breakpoints-cond.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-breakpoints.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-call-stack.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-chrome-create.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-chrome-debugging.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-console.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-debugger-buttons.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-editor-gutter.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-editor-highlight.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-editor-mode.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-editor-select.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-iframes.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-navigation.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-pause-exceptions.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-pretty-print-paused.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-pretty-print.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-scopes.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-searching.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-sourcemaps-bogus.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-sourcemaps.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-sourcemaps2.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg-sources.js
reverting devtools/client/debugger/new/test/mochitest/browser_dbg_keyboard-shortcuts.js
reverting devtools/client/debugger/new/test/mochitest/examples/README.md
reverting devtools/client/debugger/new/test/mochitest/examples/bogus-map.js
reverting devtools/client/debugger/new/test/mochitest/examples/bundle.js
reverting devtools/client/debugger/new/test/mochitest/examples/bundle.js.map
reverting devtools/client/debugger/new/test/mochitest/examples/doc-debugger-statements.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-exceptions.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-frames.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-iframes.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-minified.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-script-switching.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-scripts.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-sourcemap-bogus.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-sourcemaps.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-sourcemaps2.html
reverting devtools/client/debugger/new/test/mochitest/examples/doc-sources.html
reverting devtools/client/debugger/new/test/mochitest/examples/entry.js
reverting devtools/client/debugger/new/test/mochitest/examples/exceptions.js
reverting devtools/client/debugger/new/test/mochitest/examples/frames.js
reverting devtools/client/debugger/new/test/mochitest/examples/long.js
reverting devtools/client/debugger/new/test/mochitest/examples/math.min.js
reverting devtools/client/debugger/new/test/mochitest/examples/nested/nested-source.js
reverting devtools/client/debugger/new/test/mochitest/examples/opts.js
reverting devtools/client/debugger/new/test/mochitest/examples/output.js
reverting devtools/client/debugger/new/test/mochitest/examples/script-switching-01.js
reverting devtools/client/debugger/new/test/mochitest/examples/script-switching-02.js
reverting devtools/client/debugger/new/test/mochitest/examples/simple1.js
reverting devtools/client/debugger/new/test/mochitest/examples/simple2.js
reverting devtools/client/debugger/new/test/mochitest/examples/sourcemaps/bundle.js
reverting devtools/client/debugger/new/test/mochitest/examples/sourcemaps/bundle.js.map
reverting devtools/client/debugger/new/test/mochitest/examples/sourcemaps2/main.js
reverting devtools/client/debugger/new/test/mochitest/examples/sourcemaps2/main.js.map
reverting devtools/client/debugger/new/test/mochitest/examples/sourcemaps2/main.min.js
reverting devtools/client/debugger/new/test/mochitest/examples/times2.js
reverting devtools/client/debugger/new/test/mochitest/examples/webpack.config.js
reverting devtools/client/debugger/new/test/mochitest/head.js
reverting devtools/client/locales/en-US/debugger.properties
reverting devtools/client/preferences/devtools.js
pulling from https://hg.mozilla.org/mozilla-central/
searching for changes
no changes found
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
start: copy assets
starting: webpack
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
 0:00.25 /usr/bin/make -f client.mk -s configure
 0:01.10 cd /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend
 0:01.10 /Users/i-chun/Documents/debugger.html/firefox/configure
 0:01.28 Creating Python environment
 0:01.45 New python executable in /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/bin/python2.7
 0:01.45 Not overwriting existing python script /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/bin/python (you must use /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/bin/python2.7)
 0:01.45 Installing setuptools, pip, wheel...
 0:01.45   Complete output from command /Users/i-chun/Docume...ualenv/bin/python2.7 - setuptools pip wheel:
 0:01.45   Traceback (most recent call last):
 0:01.45   File "<stdin>", line 4, in <module>
 0:01.45   File "/Users/i-chun/anaconda/lib/python2.7/tempfile.py", line 32, in <module>
 0:01.45     import io as _io
 0:01.45   File "/Users/i-chun/anaconda/lib/python2.7/io.py", line 51, in <module>
 0:01.45     import _io
 0:01.45 ImportError: dlopen(/Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
 0:01.45   Referenced from: /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/lib/python2.7/lib-dynload/_io.so
 0:01.45   Expected in: flat namespace
 0:01.45  in /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv/lib/python2.7/lib-dynload/_io.so
 0:01.45 ----------------------------------------
 0:01.45 ...Installing setuptools, pip, wheel...done.
 0:01.45 Traceback (most recent call last):
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 2325, in <module>
 0:01.45     main()
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 711, in main
 0:01.45     symlink=options.symlink and hasattr(os, 'symlink')) # MOZ: Make sure we don't use symlink when we don't have it
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 944, in create_environment
 0:01.45     download=download,
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 900, in install_wheel
 0:01.45     call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/virtualenv/virtualenv.py", line 795, in call_subprocess
 0:01.45     % (cmd_desc, proc.returncode))
 0:01.45 OSError: Command /Users/i-chun/Docume...ualenv/bin/python2.7 - setuptools pip wheel failed with error code 1
 0:01.45 Traceback (most recent call last):
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/configure.py", line 124, in <module>
 0:01.45     sys.exit(main(sys.argv))
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/configure.py", line 29, in main
 0:01.45     sandbox.run(os.path.join(os.path.dirname(__file__), 'moz.configure'))
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 334, in run
 0:01.45     self.include_file(path)
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 325, in include_file
 0:01.45     exec_(code, self)
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/util.py", line 59, in exec_
 0:01.45     exec(object, globals, locals)
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/moz.configure", line 7, in <module>
 0:01.45     include('build/moz.configure/init.configure')
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 630, in include_impl
 0:01.45     self.include_file(what)
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 325, in include_file
 0:01.45     exec_(code, self)
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/util.py", line 59, in exec_
 0:01.45     exec(object, globals, locals)
 0:01.45   File "/Users/i-chun/Documents/debugger.html/firefox/build/moz.configure/init.configure", line 145, in <module>
 0:01.46     @imports('distutils.sysconfig')
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 613, in decorator
 0:01.46     depends = DependsFunction(self, func, dependencies, when=when)
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 69, in __init__
 0:01.46     sandbox._value_for(self)
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 409, in _value_for
 0:01.46     return self._value_for_depends(obj, need_help_dependency)
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/util.py", line 925, in method_call
 0:01.46     cache[args] = self.func(instance, *args)
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 419, in _value_for_depends
 0:01.46     return obj.result
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/util.py", line 943, in __get__
 0:01.46     setattr(instance, name, self.func(instance))
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 90, in result
 0:01.46     return self.func(*resolved_args)
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/configure/__init__.py", line 938, in wrapped
 0:01.46     return new_func(*args, **kwargs)
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/build/moz.configure/init.configure", line 192, in virtualenv_python
 0:01.46     manager.build(python)
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/virtualenv.py", line 439, in build
 0:01.46     self.create(python)
 0:01.46   File "/Users/i-chun/Documents/debugger.html/firefox/python/mozbuild/mozbuild/virtualenv.py", line 203, in create
 0:01.46     'Failed to create virtualenv: %s' % self.virtualenv_root)
 0:01.46 Exception: Failed to create virtualenv: /Users/i-chun/Documents/debugger.html/firefox/objdir-frontend/_virtualenv
 0:01.46 *** Fix above errors and then restart with               "/Applications/Xcode.app/Contents/Developer/usr/bin/make -f client.mk build"
 0:01.46 make: *** [configure] Error 1
```

**Comment by arthur801031** [comment]
`conda install python=2.7.9` fixed that error. For a more detailed explanation, please visit https://github.com/conda/conda/issues/1367.
