### ISSUE TITLE
post-merge script failing

### ISSUE THREAD

**Issue by SezginEge** [devtools-html/debugger.html#1880]
Hello,

I am getting error on post-merge script. Here there is a npm-debug.log file.

OS: Windows_NT 10.0.14393
Node: v6.9.4
Yarn: v0.19.1

```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\ege_s\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'postmerge' ]
2 info using npm@3.10.8
3 info using node@v6.9.4
4 verbose run-script [ 'postmerge' ]
5 info lifecycle debugger.html@0.0.8~postmerge: debugger.html@0.0.8
6 verbose lifecycle debugger.html@0.0.8~postmerge: unsafe-perm in lifecycle true
7 verbose lifecycle debugger.html@0.0.8~postmerge: PATH: C:\Users\ege_s\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\ege_s\Documents\GitHub\debugger.html\node_modules\.bin;C:\Users\ege_s\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\mingw32\libexec\git-core;C:\Users\ege_s\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\mingw32\libexec\git-core;C:\Users\ege_s\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\mingw32\bin;C:\Users\ege_s\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\usr\bin;C:\Users\ege_s\bin;C:\Users\ege_s\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\cmd;C:\Users\ege_s\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\usr\bin;C:\Users\ege_s\AppData\Local\GitHub\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\usr\share\git-tfs;C:\Users\ege_s\AppData\Local\Apps\2.0\X63OLAVD.RL9\GB6QQKQD.044\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\Users\ege_s\AppData\Local\GitHub\lfs-amd64_1.3.1;C:\Program Files\ImageMagick-7.0.4-Q16;C:\Python27;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\Skype\Phone;C:\Program Files (x86)\Yarn\bin;C:\Program Files\nodejs;C:\Program Files\dotnet;C:\Users\ege_s\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\ege_s\AppData\Local\Yarn\.bin;C:\Users\ege_s\AppData\Roaming\npm;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files\nodejs
8 verbose lifecycle debugger.html@0.0.8~postmerge: CWD: C:\Users\ege_s\Documents\GitHub\debugger.html
9 silly lifecycle debugger.html@0.0.8~postmerge: Args: [ '/d /s /c', 'bin/post-merge' ]
10 silly lifecycle debugger.html@0.0.8~postmerge: Returned: code: 1  signal: null
11 info lifecycle debugger.html@0.0.8~postmerge: Failed to exec postmerge script
12 verbose stack Error: debugger.html@0.0.8 postmerge: `bin/post-merge`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Users\ege_s\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at EventEmitter.emit (events.js:191:7)
12 verbose stack     at ChildProcess.<anonymous> (C:\Users\ege_s\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
12 verbose stack     at emitTwo (events.js:106:13)
12 verbose stack     at ChildProcess.emit (events.js:191:7)
12 verbose stack     at maybeClose (internal/child_process.js:877:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
13 verbose pkgid debugger.html@0.0.8
14 verbose cwd C:\Users\ege_s\Documents\GitHub\debugger.html
15 error Windows_NT 10.0.14393
16 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ege_s\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "postmerge"
17 error node v6.9.4
18 error npm  v3.10.8
19 error code ELIFECYCLE
20 error debugger.html@0.0.8 postmerge: `bin/post-merge`
20 error Exit status 1
21 error Failed at the debugger.html@0.0.8 postmerge script 'bin/post-merge'.
21 error Make sure you have the latest version of node.js and npm installed.
21 error If you do, this is most likely a problem with the debugger.html package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     bin/post-merge
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs debugger.html
21 error Or if that isn't available, you can get their info via:
21 error     npm owner ls debugger.html
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

```

**Comment by Garbee** [comment]
In the process of getting this updated shortly: https://github.com/devtools-html/debugger.html/pull/1859
