### ISSUE TITLE
yarn test fails locally

### ISSUE THREAD

**Issue by clarkbw** [devtools-html/debugger.html#2059]
When I run `yarn test` locally it fails consistently.  I get the following errors:

```bash
  80 passing (457ms)
  2 failing

  1) sources should load source text:
     SyntaxError: Unexpected token (1:8)
      at Parser.pp$5.raise (node_modules/babylon/lib/index.js:4333:13)
      at Parser.pp.unexpected (node_modules/babylon/lib/index.js:1705:8)
      at Parser.pp$1.parseFunction (node_modules/babylon/lib/index.js:2322:10)
      at Parser.pp$1.parseFunctionStatement (node_modules/babylon/lib/index.js:1999:15)
      at Parser.pp$1.parseStatement (node_modules/babylon/lib/index.js:1784:19)
      at Parser.parseStatement (node_modules/babylon/lib/index.js:5302:22)
      at Parser.pp$1.parseBlockBody (node_modules/babylon/lib/index.js:2212:21)
      at Parser.pp$1.parseTopLevel (node_modules/babylon/lib/index.js:1723:8)
      at Parser.parse (node_modules/babylon/lib/index.js:1617:17)
      at Object.parse (node_modules/babylon/lib/index.js:6657:37)

  2) sources should cache subsequent source text loads:
     SyntaxError: Unexpected token (1:8)
      at Parser.pp$5.raise (node_modules/babylon/lib/index.js:4333:13)
      at Parser.pp.unexpected (node_modules/babylon/lib/index.js:1705:8)
      at Parser.pp$1.parseFunction (node_modules/babylon/lib/index.js:2322:10)
      at Parser.pp$1.parseFunctionStatement (node_modules/babylon/lib/index.js:1999:15)
      at Parser.pp$1.parseStatement (node_modules/babylon/lib/index.js:1784:19)
      at Parser.parseStatement (node_modules/babylon/lib/index.js:5302:22)
      at Parser.pp$1.parseBlockBody (node_modules/babylon/lib/index.js:2212:21)
      at Parser.pp$1.parseTopLevel (node_modules/babylon/lib/index.js:1723:8)
      at Parser.parse (node_modules/babylon/lib/index.js:1617:17)
      at Object.parse (node_modules/babylon/lib/index.js:6657:37)
```

Can those tests be fixed or disabled?  

I'm doing all pushes with `--no-verify` now because these tests don't pass.  I'm not sure how to fix them.  Thanks!

**Comment by bomsy** [comment]
I hit this issue too. The sample js source text used in test has syntax errors. I'll push my fix for the tests.

**Comment by clarkbw** [comment]
This should be fixed now!
