### ISSUE TITLE
Debugger server doesn't run on windows

### ISSUE THREAD

**Issue by samjwalker** [devtools-html/debugger.html#2416]
I get this error message when running `yarn start` on windows

```ERROR in ./~/devtools-source-map/src/worker.js
Module parse failed: C:\Users\***\projects\debugger.html\node_modules\devtools-source-map\src\worker.js Unexpected token (21:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (21:12)
    at Parser.pp$4.raise (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.expectContextual (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:558:41)
    at Parser.pp$1.parseImport (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:1240:12)
    at Parser.pp$1.parseStatement (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:719:46)
    at Parser.pp$1.parseTopLevel (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\***\projects\debugger.html\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (C:\Users\***\projects\debugger.html\node_modules\webpack\lib\NormalModule.js:104:16)
 @ multi source-map-worker

ERROR in ./~/devtools-source-map/src/index.js
Module parse failed: C:\Users\***\projects\debugger.html\node_modules\devtools-source-map\src\index.js Unexpected token (12:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (12:12)
    at Parser.pp$4.raise (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.expectContextual (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:558:41)
    at Parser.pp$1.parseImport (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:1240:12)
    at Parser.pp$1.parseStatement (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:719:46)
    at Parser.pp$1.parseTopLevel (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\***\projects\debugger.html\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (C:\Users\***\projects\debugger.html\node_modules\webpack\lib\NormalModule.js:104:16)
 @ ./src/main.js 73:18-48

ERROR in ./~/devtools-launchpad/src/index.js
Module parse failed: C:\Users\***\projects\debugger.html\node_modules\devtools-launchpad\src\index.js Unexpected token (51:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (51:6)
    at Parser.pp$4.raise (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\***\projects\debugger.html\node_modules\webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\***\projects\debugger.html\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (C:\Users\***\projects\debugger.html\node_modules\webpack\lib\NormalModule.js:104:16)
 @ ./src/main.js 15:16-45
```

**Comment by sammyjimtb** [comment]
This is the config we're actually sending to webpack. Maybe there is a path separator problem?!?

```{
"entry": {
 "debugger": [
  "C:\\Users\\****\\projects\\mozilla\\debugger.html\\src\\main.js"
 ],
 "source-map-worker": [
  "C:\\Users\\****\\projects\\mozilla\\debugger.html\\node_modules\\devtools-source-map\\src\\worker.js"
 ],
 "parser-worker": [
  "C:\\Users\\****\\projects\\mozilla\\debugger.html\\src\\utils\\parser\\worker.js"
 ],
 "pretty-print-worker": [
  "C:\\Users\\****\\projects\\mozilla\\debugger.html\\src\\utils\\pretty-print-worker.js"
 ],
 "integration-tests": [
  "C:\\Users\\****\\projects\\mozilla\\debugger.html\\src\\test\\integration\\tests.js"
 ]
},
"output": {
 "path": "C:\\Users\\****\\projects\\mozilla\\debugger.html\\assets\\build",
 "filename": "[name].js",
 "publicPath": "/assets/build",
 "libraryTarget": "umd"
},
"resolve": {
 "alias": {
  "react-dom": "react-dom/dist/react-dom",
  "react": "react/lib/ReactUMDEntry"
 }
},
"context": "C:\\Users\\****\\projects\\mozilla\\debugger.html\\node_modules\\devtools-launchpad\\src",
"devtool": "source-map",
"module": {
 "loaders": [
  {
   "test": {},
   "loader": "json"
  },
  {
   "test": {},
   "loaders": [
    "babel?plugins[]=transform-flow-strip-types,plugins[]=transform-async-to-generator&ignore=src/lib"
   ],
   "isJavaScriptLoader": true
  },
  {
   "test": {},
   "exclude": {},
   "loader": "svg-inline"
  },
  {
   "test": {},
   "loader": "style!css!postcss"
  }
 ]
},
"resolveLoader": {
 "root": [
  "C:\\Users\\****\\projects\\mozilla\\debugger.html\\node_modules"
 ]
},
"node": {
 "fs": "empty"
},
"plugins": [
 {
  "definitions": {
   "process.env": {
    "NODE_ENV": "\"development\"",
    "TARGET": "\"local\""
   },
   "DebuggerConfig": "{\"title\":\"Debugger\",\"environment\":\"development\",\"baseWorkerURL\":\"http://localhost:8000/assets/build/\",\"sourceMapWorkerURL\":\"http://localhost:8000/assets/build/source-map-worker.js\",\"favicon\":\"assets/images/favicon.png\",\"theme\":\"light\",\"dir\":\"ltr\",\"logging\":{\"client\":false,\"firefoxProxy\":false,\"actions\":false},\"features\":{\"watchExpressions\":{\"label\":\"Watch Expressions\",\"enabled\":true},\"chromeScopes\":{\"label\":\"Chrome Scopes\",\"enabled\":false},\"eventListeners\":{\"label\":\"Event Listeners\",\"enabled\":false},\"codeCoverage\":{\"label\":\"Code Coverage\",\"enabled\":false},\"searchModifiers\":{\"label\":\"Search Modifiers\",\"enabled\":true},\"symbolSearch\":{\"label\":\"Symbol Search\",\"enabled\":false},\"functionSearch\":{\"label\":\"function Search\",\"enabled\":true},\"editorPreview\":{\"label\":\"Editor Preview\",\"enabled\":true},\"previewMemberExpressions\":{\"label\":\"Editor member expression Preview\",\"enabled\":true}},\"chrome\":{\"debug\":true,\"host\":\"localhost\",\"port\":9222},\"node\":{\"debug\":true,\"host\":\"localhost\",\"port\":9229},\"firefox\":{\"webSocketConnection\":false,\"proxyHost\":\"localhost:9000\",\"webSocketHost\":\"localhost:6080\",\"mcPath\":\"./firefox\"},\"development\":{\"serverPort\":8000,\"examplesPort\":7999}}"
  }
 }
]
}```

**Comment by jasonLaster** [comment]
Thanks for the helpful patches [here](https://github.com/devtools-html/devtools-core/blame/master/packages/devtools-launchpad/webpack.config.js#L44) is where we decide what to modules in `node_modules` to babel transform. We used to add the path like this `\/` [here](https://github.com/devtools-html/devtools-core/blame/1d9282d9221ce8fcf8576ceb00c5d1e5803ffa66/packages/devtools-launchpad/webpack.config.js#L47). Mind trying the old way in your `node_modules/devtools-launchpad/webpack.config.js` and letting me us know what you find?

**Comment by jasonLaster** [comment]
Fix is coming in the new launchpad
