### ISSUE TITLE
WebDriverError: Missing 'marionetteProtocol' field in handshake

### ISSUE THREAD

**Issue by Erica42** [devtools-html/debugger.html#2470]
So this is weird.
```
/Users/ecca/projects/debugger.html/node_modules/selenium-webdriver/lib/promise.js:2634
        throw error;
        ^

WebDriverError: Missing 'marionetteProtocol' field in handshake
    at Object.throwDecodedError (/Users/ecca/projects/debugger.html/node_modules/selenium-webdriver/lib/error.js:489:11)
    at parseHttpResponse (/Users/ecca/projects/debugger.html/node_modules/selenium-webdriver/lib/http.js:513:13)
    at doSend.then.response (/Users/ecca/projects/debugger.html/node_modules/selenium-webdriver/lib/http.js:432:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/ecca/projects/debugger.html/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/Users/ecca/projects/debugger.html/node_modules/selenium-webdriver/firefox/index.js:667:55)
    at createDriver (/Users/ecca/projects/debugger.html/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/Users/ecca/projects/debugger.html/node_modules/selenium-webdriver/index.js:642:16)
    at start (/Users/ecca/projects/debugger.html/node_modules/devtools-launchpad/bin/firefox-driver.js:74:6)
    at Object.<anonymous> (/Users/ecca/projects/debugger.html/node_modules/devtools-launchpad/bin/firefox-driver.js:87:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jasonLaster** [comment]
Thanks @Erica42 - this is the first time we've seen this error, but I believe geckodriver and selenium *are* updating.

What OS are you using. Also, what version of `geckodriver` and `selenium-webdriver` do you have?

Lastly, are you in our https://devtools-html-slack.herokuapp.com slack room?

**Comment by jasonLaster** [comment]
I think this might be a firefox version thing: https://github.com/mozilla/geckodriver/issues/85#issuecomment-226571803

Try updating firefox

**Comment by jasonLaster** [comment]
Closing this as it looks like it's a firefox version issue.

Feel free to re-open if you still see it
