### ISSUE TITLE
[launchpad] firefox is not launching

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#2730]
I broke the firefox driver last week when I refactored the launchpad / devtools-modules. https://github.com/devtools-html/devtools-core/commits/master

I think it's a simple dependency issue because when I install geckodriver locally in debugger.html it works

Here's the error I'm seeing:

<img src='https://shipusercontent.com/097b869fe5926cc423de6058b3cc39e7/Screen%20Shot%202017-04-25%20at%2011.42.22%20AM.png' title='Screen Shot 2017-04-25 at 11.42.22 AM.png' width=1429>

**Comment by jasonLaster** [comment]
It looks like if I peg the selenium version to `3.3.0` it works but gives this warning:

```

WebDriverError: Unable to parse new session response: {"sessionId":"41f25eb2-cb29-c446-8f14-c21d67b3795b","value":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"52.0.1","moz:accessibilityChecks":false,"moz:processID":99699,"moz:profile":"/var/folders/wn/0pxdh48551d4xw9h93k3bb600000gn/T/rust_mozprofile.YKPs1RSlT6An","pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"16.5.0","rotatable":false,"specificationLevel":0,"timeouts":{"implicit":0,"page load":300000,"script":30000}}}
    at doSend.then.response (/Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-launchpad/node_modules/selenium-webdriver/lib/http.js:446:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-launchpad/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-launchpad/node_modules/selenium-webdriver/firefox/index.js:667:55)
    at createDriver (/Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-launchpad/node_modules/selenium-webdriver/index.js:167:33)
    at Builder.build (/Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-launchpad/node_modules/selenium-webdriver/index.js:642:16)
    at start (/Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-launchpad/bin/firefox-driver.js:75:6)
    at Object.<anonymous> (/Users/jlaster/src/mozilla/debugger.html/node_modules/devtools-launchpad/bin/firefox-driver.js:88:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    ```
