### ISSUE TITLE
Yarn 0.27.5 breaks CI, jest, and flow

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#3489]
This is a tracking ticket for our issues with the most recent yarn, which we should check -- see what is on our side and what is really failing

so far we have had these failures:

- `yarn nom` introduces `react-dom-factories` which has an incompatible version of react for us. This cause `yarn check` to fail with this error [1].
- a fresh install will try to install `fsevents@1.1.1` -- which fails with a warning
- a number of contributors have gotten the following error:

```
TypeError: projects.map is not a function
    at Object.<anonymous> (/media/amelzer/WORKEXT4/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:112:28)
    at next (native)
    at step (/media/amelzer/WORKEXT4/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:1:260)
    at /media/amelzer/WORKEXT4/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:1:490
    at Object.<anonymous> (/media/amelzer/WORKEXT4/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:1:171)
    at Object.module.exports [as runCLI] (/media/amelzer/WORKEXT4/debugger.html/node_modules/jest-cli/build/cli/runCLI.js:139:50)
    at Object.run (/media/amelzer/WORKEXT4/debugger.html/node_modules/devtools-source-map/node_modules/jest-cli/build/cli/index.js:42:17)
    at Object.<anonymous> (/media/amelzer/WORKEXT4/debugger.html/node_modules/devtools-source-map/node_modules/jest-cli/bin/jest.js:16:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

#### [1] yarn check

```
yarn check
yarn check v0.24.5
⠁ ⠂ babel-register@^6.18.0⠄ source-map-support@^0.4.2⡀ os-tmpdir@^1.0.1⢀ indexof@0.0.1⠠ get-stdin@^4.0.1⠐ align-text@^0.1.1warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
error "react-modal#react-dom-factories#react@^15.5.4" doesn't satisfy found match of "react@15.3.2"
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.

yarn check returned exit code 1
```
https://circleci.com/gh/devtools-html/debugger.html/5615

**Comment by jasonLaster** [comment]
If you run into this revert to 24.5

` npm install yarn@0.24.5 -g`

**Comment by jasonLaster** [comment]
turns out the fix was bumping jest... but we got a better yarn for everyone too
