### ISSUE TITLE
pre-push hook: projects.map is not a function

### ISSUE THREAD

**Issue by nyrosmith** [devtools-html/debugger.html#3641]
I just tried to push changes to my fork and ran into this error:

```
husky > npm run -s prepush (node v8.2.1)

TypeError: projects.map is not a function
    at Object.<anonymous> (E:\github\debugger.html\node_modules\jest-cli\build\cli\runCLI.js:112:28)
    at Generator.next (<anonymous>)
    at step (E:\github\debugger.html\node_modules\jest-cli\build\cli\runCLI.js:1:260)
    at E:\github\debugger.html\node_modules\jest-cli\build\cli\runCLI.js:1:490
    at Promise (<anonymous>)
    at Object.<anonymous> (E:\github\debugger.html\node_modules\jest-cli\build\cli\runCLI.js:1:171)
    at Object.module.exports [as runCLI] (E:\github\debugger.html\node_modules\jest-cli\build\cli\runCLI.js:139:50)
    at Object.run (E:\github\debugger.html\node_modules\devtools-launchpad\node_modules\jest-cli\build\cli\index.js:42:17)
    at Object.<anonymous> (E:\github\debugger.html\node_modules\devtools-launchpad\node_modules\jest-cli\bin\jest.js:16:25)
    at Module._compile (module.js:569:30)
```

I already verified that I don't have jest installed globally.
Maybe it's bc I am running on Windows?

**Comment by bomsy** [comment]
I think we can close this .

**Comment by nyrosmith** [comment]
Is this fixed now @bomsy

**Comment by nyrosmith** [comment]
I just pulled master and still have this error @bomsy

**Comment by bomsy** [comment]
Yeah this is an issue a version of jest or so..

@jasonLaster There was something mentioned about an update that fixed this issue, correct?

**Comment by nyrosmith** [comment]
Yarn run nom was suggested but rm -rf does not work on Windows....

**Comment by nyrosmith** [comment]
And I think this workaround should be referenced in the docs
