### ISSUE TITLE
CI Jest intermittent

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#3761]
```
jest -i --testResultsProcessor jest-junit-reporter --coverage --coverageDirectory=$CIRCLE_TEST_REPORTS/jest-coverage
 PASS  src/actions/tests/pending-breakpoints.spec.js (11.346s)
 PASS  src/actions/tests/breakpoints.spec.js
 PASS  src/actions/tests/sources.spec.js
 PASS  src/utils/search/tests/build-query.spec.js
 PASS  src/utils/sources-tree/tests/addToTree.spec.js
 PASS  src/utils/sources-tree/tests/sortTree.spec.js
 PASS  src/utils/sources-tree/tests/utils.spec.js
 PASS  src/utils/tests/scopes.spec.js
 PASS  src/actions/tests/ui.spec.js
 PASS  src/actions/tests/ast.spec.js
 PASS  src/actions/tests/tabs.spec.js
 PASS  src/utils/sources-tree/tests/collapseTree.spec.js
 PASS  src/components/tests/previewFunction.spec.js
 PASS  src/components/SecondaryPanes/Frames/tests/Frames.js
 PASS  src/utils/parser/tests/scopes.spec.js
 PASS  src/components/SecondaryPanes/Frames/tests/FrameMenu.js
 PASS  src/utils/tests/source.spec.js
 PASS  src/actions/tests/expressions.spec.js
 PASS  src/components/Editor/tests/DebugLine.js
 PASS  src/actions/tests/project-text-search.spec.js
 PASS  src/utils/tests/frame.spec.js
 PASS  src/utils/tests/wasm.spec.js
 PASS  src/utils/parser/tests/closest.spec.js
 PASS  src/utils/search/tests/get-matches.spec.js
 PASS  src/components/SecondaryPanes/Frames/tests/Frame.js
 PASS  src/client/firefox/tests/commands.spec.js
 PASS  src/components/tests/Outline.spec.js
 PASS  src/reducers/tests/breakpoints.spec.js
 PASS  src/components/Editor/tests/SearchBar.spec.js
 PASS  src/components/Editor/tests/Breakpoints.spec.js
 PASS  src/components/SecondaryPanes/tests/Expressions.spec.js
 PASS  src/utils/parser/tests/getSymbols.spec.js
 PASS  src/components/tests/SymbolModal.spec.js
 PASS  src/actions/tests/pause.spec.js
 PASS  src/components/SecondaryPanes/Frames/tests/Group.js
 PASS  src/utils/parser/tests/getOutOfScopeLocations.spec.js
 PASS  src/utils/tests/fromJS.spec.js
 PASS  src/components/tests/resultList.spec.js
 PASS  src/components/tests/WhyPaused.spec.js
 PASS  src/components/Editor/tests/Editor.spec.js
 PASS  src/client/firefox/tests/onconnect.spec.js
 PASS  src/reducers/tests/ui.spec.js
 PASS  src/actions/sources/tests/createPrettySource.js
/home/ubuntu/debugger.html/node_modules/devtools-utils/src/worker-utils.js:48
          this.worker.removeEventListener("message", listener);
                     ^

TypeError: Cannot read property 'removeEventListener' of null
    at Worker.listener (/home/ubuntu/debugger.html/node_modules/devtools-utils/src/worker-utils.js:48:22)
    at self.handlers.message.forEach.func (/home/ubuntu/debugger.html/node_modules/workerjs/index.js:25:53)
    at Array.forEach (native)
    at ChildProcess.<anonymous> (/home/ubuntu/debugger.html/node_modules/workerjs/index.js:25:32)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

jest -i --testResultsProcessor jest-junit-reporter --coverage --coverageDirectory=$CIRCLE_TEST_REPORTS/jest-coverage returned exit code 1
```

**Comment by jasonLaster** [comment]
alright - the intermittent test is `createPrettySource`

**Comment by codehag** [comment]
Thanks for the write up and investigation! was just about to do the same

**Comment by jasonLaster** [comment]
i think theres another int
