### ISSUE TITLE
Tests failing after `yarn nom`

### ISSUE THREAD

**Issue by codehag** [devtools-html/debugger.html#4348]
Steps to reproduce:

`yarn nom; yarn test` 

expected: tests pass
actual:

```
Summary of all failing tests
 FAIL  components/tests/SymbolModal.spec.js
  ● SymbolModal › should render

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -14,26 +14,10 @@
                       </Svg>
                       <input className="" onChange={[Function]} onKeyDown={[undefined]} onKeyUp={[Function]} onFocus={[undefined]} onBlur={[undefined]} placeholder="Search functions…" value="" spellCheck={false} />
                       <div className="summary">
                         1 of 2 results
                       </div>
    -                  <div className="search-nav-buttons">
    -                    <button onClick={[Function]} type="arrow-down" className="nav-btn next" title="Next result">
    -                      <Svg name="arrow-down">
    -                        <InlineSVG className="arrow-down " onClick={[undefined]} aria-label={[undefined]} src="<svg></svg>" element="i" raw={false}>
    -                          <i className="arrow-down " onClick={[undefined]} aria-label={[undefined]} src={{...}} dangerouslySetInnerHTML={{...}} />
    -                        </InlineSVG>
    -                      </Svg>
    -                    </button>
    -                    <button onClick={[Function]} type="arrow-up" className="nav-btn prev" title="Previous result">
    -                      <Svg name="arrow-up">
    -                        <InlineSVG className="arrow-up " onClick={[undefined]} aria-label={[undefined]} src="<svg></svg>" element="i" raw={false}>
    -                          <i className="arrow-up " onClick={[undefined]} aria-label={[undefined]} src={{...}} dangerouslySetInnerHTML={{...}} />
    -                        </InlineSVG>
    -                      </Svg>
    -                    </button>
    -                  </div>
                       <CloseButton handleClick={[Function]} buttonClass="">
                         <div className="close-btn" onClick={[Function]} title={[undefined]}>
                           <Svg name="close">
                             <InlineSVG className="close " onClick={[undefined]} aria-label={[undefined]} src="<svg></svg>" element="i" raw={false}>
                               <i className="close " onClick={[undefined]} aria-label={[undefined]} src={{...}} dangerouslySetInnerHTML={{...}} />

      at Object.it (src/components/tests/SymbolModal.spec.js:68:31)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)


Snapshot Summary
 › 1 snapshot test failed in 1 test suite. Inspect your code changes or press `u` to update them.

Test Suites: 1 failed, 60 passed, 61 total
Tests:       1 failed, 343 passed, 344 total
Snapshots:   1 failed, 111 passed, 112 total
Time:        43.024s, estimated 389s
Ran all test suites.

✨  Done in 659.24s.
Ystartsev@ystartsevv-35339:~/Work/debugger.html|master⚡
⇒  yarn test
yarn test v0.24.5
$ jest
 FAIL  src/components/tests/SymbolModal.spec.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

  ● SymbolModal › should render

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -14,26 +14,10 @@
                       </Svg>
                       <input className="" onChange={[Function]} onKeyDown={[undefined]} onKeyUp={[Function]} onFocus={[undefined]} onBlur={[undefined]} placeholder="Search functions…" value="" spellCheck={false} />
                       <div className="summary">
                         1 of 2 results
                       </div>
    -                  <div className="search-nav-buttons">
    -                    <button onClick={[Function]} type="arrow-down" className="nav-btn next" title="Next result">
    -                      <Svg name="arrow-down">
    -                        <InlineSVG className="arrow-down " onClick={[undefined]} aria-label={[undefined]} src="<svg></svg>" element="i" raw={false}>
    -                          <i className="arrow-down " onClick={[undefined]} aria-label={[undefined]} src={{...}} dangerouslySetInnerHTML={{...}} />
    -                        </InlineSVG>
    -                      </Svg>
    -                    </button>
    -                    <button onClick={[Function]} type="arrow-up" className="nav-btn prev" title="Previous result">
    -                      <Svg name="arrow-up">
    -                        <InlineSVG className="arrow-up " onClick={[undefined]} aria-label={[undefined]} src="<svg></svg>" element="i" raw={false}>
    -                          <i className="arrow-up " onClick={[undefined]} aria-label={[undefined]} src={{...}} dangerouslySetInnerHTML={{...}} />
    -                        </InlineSVG>
    -                      </Svg>
    -                    </button>
    -                  </div>
                       <CloseButton handleClick={[Function]} buttonClass="">
                         <div className="close-btn" onClick={[Function]} title={[undefined]}>
                           <Svg name="close">
                             <InlineSVG className="close " onClick={[undefined]} aria-label={[undefined]} src="<svg></svg>" element="i" raw={false}>
                               <i className="close " onClick={[undefined]} aria-label={[undefined]} src={{...}} dangerouslySetInnerHTML={{...}} />

      at Object.it (src/components/tests/SymbolModal.spec.js:68:31)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

 PASS  src/actions/tests/sources.spec.js
 PASS  src/actions/tests/breakpoints.spec.js
 PASS  src/actions/tests/pending-breakpoints.spec.js
 PASS  src/actions/tests/ast.spec.js
 PASS  src/actions/tests/tabs.spec.js
 PASS  src/utils/breakpoint/tests/astBreakpointLocation.spec.js
 PASS  src/actions/sources/tests/createPrettySource.js
 PASS  src/actions/tests/project-text-search.spec.js
 PASS  src/workers/parser/tests/getSymbols.spec.js

 RUNS  src/actions/tests/pause.spec.js
 RUNS  src/actions/tests/expressions.spec.js
 PASS  src/actions/tests/expressions.spec.jspec.js
 PASS  src/actions/tests/pause.spec.js
 PASS  src/components/ProjectSearch/tests/TextSearch.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

 PASS  src/workers/parser/tests/getOutOfScopeLocations.spec.js
 PASS  src/workers/parser/tests/getEmptyLines.js
 PASS  src/workers/parser/tests/closest.spec.js
 PASS  src/components/Editor/tests/Editor.spec.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

 PASS  src/utils/tests/function.spec.js
 PASS  src/workers/parser/tests/validate.spec.js
 PASS  src/components/SecondaryPanes/Frames/tests/Frames.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

 PASS  src/components/tests/Outline.spec.js
 PASS  src/components/Editor/tests/SearchBar.spec.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

 PASS  src/components/SecondaryPanes/tests/Expressions.spec.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

 PASS  src/components/SecondaryPanes/Frames/tests/Group.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

 PASS  src/components/Editor/tests/Breakpoints.spec.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

 PASS  src/components/tests/resultList.spec.js
 PASS  src/components/tests/closeButton.spec.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

 PASS  src/components/Editor/tests/DebugLine.js
 PASS  src/components/SecondaryPanes/Frames/tests/Frame.js
  ● Console

    console.warn node_modules/react/lib/lowPriorityWarning.js:38
      Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

 PASS  src/utils/tests/indentation.spec.js
 PASS  src/reducers/tests/ui.spec.js
 PASS  src/components/tests/PreviewFunction.spec.js
 PASS  src/components/tests/WhyPaused.spec.js
 PASS  src/utils/tests/wasm.spec.js
 PASS  src/workers/parser/tests/steps.spec.js
 PASS  src/utils/tests/DevToolsUtils.spec.js
 PASS  src/utils/tests/source.spec.js
 PASS  src/actions/tests/ui.spec.js
 PASS  src/utils/sources-tree/tests/addToTree.spec.js
 PASS  src/workers/parser/tests/scopes.spec.js
 PASS  src/components/ProjectSearch/textSearch/tests/textSearch.spec.js
 PASS  src/actions/tests/source-tree.spec.js
 PASS  src/utils/sources-tree/tests/collapseTree.spec.js
 PASS  src/client/firefox/tests/onconnect.spec.js
 PASS  src/workers/parser/tests/sources.spec.js
 PASS  src/reducers/tests/breakpoints.spec.js
 PASS  src/actions/tests/navigation.spec.js
 PASS  src/actions/breakpoints/tests/syncing.js
 PASS  src/client/firefox/tests/commands.spec.js
 PASS  src/utils/tests/expressions.spec.js
 PASS  src/utils/tests/source-search.spec.js
 PASS  src/components/SecondaryPanes/Frames/tests/FrameMenu.js
 PASS  src/utils/tests/scopes.spec.js
 PASS  src/utils/sources-tree/tests/utils.spec.js
 PASS  src/workers/search/tests/get-matches.spec.js
 PASS  src/workers/search/tests/build-query.spec.js
 PASS  src/utils/sources-tree/tests/sortTree.spec.js
 PASS  src/workers/search/tests/project-search.spec.js
 PASS  src/utils/tests/fromJS.spec.js
 PASS  src/utils/tests/frame.spec.js
 PASS  src/reducers/tests/sources.spec.js

Summary of all failing tests
 FAIL  components/tests/SymbolModal.spec.js
  ● SymbolModal › should render

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot 1.

    - Snapshot
    + Received

    @@ -14,26 +14,10 @@
                       </Svg>
                       <input className="" onChange={[Function]} onKeyDown={[undefined]} onKeyUp={[Function]} onFocus={[undefined]} onBlur={[undefined]} placeholder="Search functions…" value="" spellCheck={false} />
                       <div className="summary">
                         1 of 2 results
                       </div>
    -                  <div className="search-nav-buttons">
    -                    <button onClick={[Function]} type="arrow-down" className="nav-btn next" title="Next result">
    -                      <Svg name="arrow-down">
    -                        <InlineSVG className="arrow-down " onClick={[undefined]} aria-label={[undefined]} src="<svg></svg>" element="i" raw={false}>
    -                          <i className="arrow-down " onClick={[undefined]} aria-label={[undefined]} src={{...}} dangerouslySetInnerHTML={{...}} />
    -                        </InlineSVG>
    -                      </Svg>
    -                    </button>
    -                    <button onClick={[Function]} type="arrow-up" className="nav-btn prev" title="Previous result">
    -                      <Svg name="arrow-up">
    -                        <InlineSVG className="arrow-up " onClick={[undefined]} aria-label={[undefined]} src="<svg></svg>" element="i" raw={false}>
    -                          <i className="arrow-up " onClick={[undefined]} aria-label={[undefined]} src={{...}} dangerouslySetInnerHTML={{...}} />
    -                        </InlineSVG>
    -                      </Svg>
    -                    </button>
    -                  </div>
                       <CloseButton handleClick={[Function]} buttonClass="">
                         <div className="close-btn" onClick={[Function]} title={[undefined]}>
                           <Svg name="close">
                             <InlineSVG className="close " onClick={[undefined]} aria-label={[undefined]} src="<svg></svg>" element="i" raw={false}>
                               <i className="close " onClick={[undefined]} aria-label={[undefined]} src={{...}} dangerouslySetInnerHTML={{...}} />

      at Object.it (src/components/tests/SymbolModal.spec.js:68:31)
          at Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)


Snapshot Summary
 › 1 snapshot test failed in 1 test suite. Inspect your code changes or run with `yarn test -- -u` to update them.

Test Suites: 1 failed, 60 passed, 61 total
Tests:       1 failed, 343 passed, 344 total
Snapshots:   1 failed, 111 passed, 112 total
Time:        25.724s, estimated 32s
Ran all test suites.
error Command failed with exit code 1.
```

**Comment by nyrosmith** [comment]
@codehag Not every dep in our package.json is pinned to an exact version. 
Deleting yarn.lock and running install afterwards may result in installed versions of dependencies that may have breaking changes.
Unfortunately not every author respects SemVer and sometimes a fix for a lib can result in a breaking change if the consumer has already implemented a workaround or relies on that behavior.

I see two possible fixes:

1. Stop swiping the yarn.lock file on `nom`
2. Pin every dep to an exact version

**Comment by jasonLaster** [comment]
we should probably just do a `yarn nom`, fix the tests, and `commit the new lock and tests`

**Comment by jasonLaster** [comment]
not seeing this now
