### ISSUE TITLE
[PrettyPrint] pretty printing a source should open the pretty printed tab

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#4647]
Clicking the pretty print icon doesn't focus on the newly created pretty print tab

We used to support this, but i think we regressed recently.

**Comment by jasonLaster** [comment]
Alright, so i narrowed the bug down to `selectSource` not selecting the source :) 

I also added some mochitest stuff so it's easy to run `yarn mochid browser_dbg-pretty-print.js` and `yarn mochih browser_dbg-pretty-print.js`

[mochitests](https://github.com/devtools-html/debugger.html/blob/master/docs/mochitests.md)

I think the fix will likely be in `reducers/sources`

```diff
diff --git a/src/actions/sources.js b/src/actions/sources.js
index 79df46b..7bb22b1 100644
--- a/src/actions/sources.js
+++ b/src/actions/sources.js
@@ -338,7 +338,11 @@ export function togglePrettyPrint(sourceId: string) {
     await dispatch(remapBreakpoints(sourceId));
     await dispatch(setEmptyLines(newPrettySource.id));
 
-    return dispatch(selectSource(newPrettySource.id, options));
+    await dispatch(selectSource(newPrettySource.id, options));
+    debugger;
+
+    // the selected location didn't chante
+    dump(`>>> ${getState().sources.toJS().selectedLocation}`);
   };
 }
 
diff --git a/src/test/mochitest/browser_dbg-pretty-print.js b/src/test/mochitest/browser_dbg-pretty-print.js
index 846aab4..6254a9b 100644
--- a/src/test/mochitest/browser_dbg-pretty-print.js
+++ b/src/test/mochitest/browser_dbg-pretty-print.js
@@ -9,9 +9,11 @@ add_task(async function() {
   await selectSource(dbg, "math.min.js", 2);
   clickElement(dbg, "prettyPrintButton");
 
-  await waitForSource(dbg, "math.min.js:formatted");
+  await waitForSelectedSource(dbg, "math.min.js:formatted");
   const ppSrc = findSource(dbg, "math.min.js:formatted");
 
+  debugger;
+
   ok(ppSrc, "Pretty-printed source exists");
 
   // this is not implemented yet
diff --git a/src/test/mochitest/head.js b/src/test/mochitest/head.js
index 6fa3440..09224a6 100644
--- a/src/test/mochitest/head.js
+++ b/src/test/mochitest/head.js
@@ -230,6 +230,11 @@ async function waitForElement(dbg, selector) {
   return findElementWithSelector(dbg, selector);
 }
 
+
+/*
+ * waits for a source to be selected and fully loaded
+ * for instance has the symbols parsed
+ */
 function waitForSelectedSource(dbg, url) {
   return waitForState(
     dbg,
@@ -244,11 +249,18 @@ function waitForSelectedSource(dbg, url) {
         return true;
       }
 
-      const newSource = findSource(dbg, url);
+      const newSource = findSource(dbg, url, { silent: true });
+      if (!newSource) {
+        return false;
+      }
+
       if (newSource.id != source.get("id")) {
         return false;
       }
 
+      log(`wait for selected source`, { source })
+
+
       // wait for async work to be done
       return dbg.selectors.hasSymbols(state, source.toJS());
     },
@@ -519,7 +531,7 @@ function pauseTest() {
  * @return {Object} source
  * @static
  */
-function findSource(dbg, url) {
+function findSource(dbg, url, { silent } = {silent: true}) {
   if (typeof url !== "string") {
     // Support passing in a source object itelf all APIs that use this
     // function support both styles
@@ -530,7 +542,13 @@ function findSource(dbg, url) {
   const sources = dbg.selectors.getSources(dbg.getState());
   const source = sources.find(s => (s.get("url") || "").includes(url));
 
+
+
   if (!source) {
+    if (silent) {
+      return false;
+    }
+
     throw new Error(`Unable to find source: ${url}`);
   }
 
```

**Comment by hughugsy** [comment]
Hey! :smile: This fixes the issue
```
--- a/src/reducers/sources.js
+++ b/src/reducers/sources.js
@@ -52,7 +52,7 @@ function update(
   action: Action
 ): Record<SourcesState> {
   let location = null;
-
+  let sourceID = null;
   switch (action.type) {
     case "ADD_SOURCE": {
       const source = action.source;
@@ -76,12 +76,15 @@ function update(
         ...action.location,
         url: action.source.url
       };
+      sourceID = {
+        sourceId: action.source.id
+      };
 
       prefs.pendingSelectedLocation = location;
       return state
         .set("selectedLocation", {
-          sourceId: action.source.id,
-          ...action.location
+          sourceId: action.location.sourceId,
+          ...sourceID
         })
         .set("pendingSelectedLocation", location);

```
but I couldn't set up mochitests to run and `yarn test` results in these
```
Summary of all failing tests
 FAIL  actions/tests/sources.spec.js (12.868s)
  ● sources › should select a source

    TypeError: Cannot read property 'length' of null
      
      at Object.<anonymous> (src/actions/tests/sources.spec.js:59:21)
          at Generator.next (<anonymous>)
      at step (src/actions/tests/sources.spec.js:16:242)
      at src/actions/tests/sources.spec.js:16:402
          at <anonymous>

 FAIL  actions/tests/ast.spec.js (10.363s)
  ● ast › getOutOfScopeLocations › with selected line

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Array [
      Object {
        "end": Object {
          "column": 16,
          "line": 1,
        },
        "start": Object {
          "column": 0,
          "line": 1,
        },
      },
      Object {
        "end": Object {
          "column": 3,
          "line": 10,
        },
        "start": Object {
          "column": 22,
          "line": 8,
        },
      },
    ]
    + null
      
      at Object.<anonymous> (src/actions/tests/ast.spec.js:150:25)
          at Generator.next (<anonymous>)
      at step (src/actions/tests/ast.spec.js:18:397)
      at src/actions/tests/ast.spec.js:18:557
          at <anonymous>

  ● ast › getOutOfScopeLocations › with selected line

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 2.
    
    - Snapshot
    + Received
    
    @@ -4,9 +4,11 @@
       3,
       4,
       5,
       6,
       7,
    +  8,
    +  9,
       10,
       11,
       12,
     ]
      
      at Object.<anonymous> (src/actions/tests/ast.spec.js:151:21)
          at Generator.next (<anonymous>)
      at step (src/actions/tests/ast.spec.js:18:397)
      at src/actions/tests/ast.spec.js:18:557
          at <anonymous>

  ● ast › getOutOfScopeLocations › without a selected line

    expect(received).toEqual(expected)
    
    Expected value to equal:
      [1]
    Received:
      [1, 2, 3]
    
    Difference:
    
    - Expected
    + Received
    
     Array [
       1,
    +  2,
    +  3,
     ]
      
      at Object.<anonymous> (src/actions/tests/ast.spec.js:164:21)
          at Generator.next (<anonymous>)
      at step (src/actions/tests/ast.spec.js:18:397)
      at src/actions/tests/ast.spec.js:18:557
          at <anonymous>

  ● ast › setPreview › member expression

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Object {
      "cursorPos": undefined,
      "expression": "this.bazz",
      "extra": undefined,
      "location": Object {
        "end": Object {
          "column": 37,
          "line": 1,
        },
        "start": Object {
          "column": 33,
          "line": 1,
        },
      },
      "result": Object {
        "actor": "bazz",
        "preview": Object {},
      },
      "tokenPos": Object {
        "column": 34,
        "line": 1,
      },
      "updating": false,
    }
    + null
      
      at Object.<anonymous> (src/actions/tests/ast.spec.js:192:23)
          at Generator.next (<anonymous>)
      at step (src/actions/tests/ast.spec.js:18:397)
      at src/actions/tests/ast.spec.js:18:557
          at <anonymous>

  ● ast › setPreview › this

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Object {
      "cursorPos": undefined,
      "expression": "this",
      "extra": undefined,
      "location": Object {
        "end": Object {
          "column": 32,
          "line": 1,
        },
        "start": Object {
          "column": 28,
          "line": 1,
        },
      },
      "result": Object {
        "actor": "this",
        "preview": Object {},
      },
      "tokenPos": Object {
        "column": 30,
        "line": 1,
      },
      "updating": false,
    }
    + null
      
      at Object.<anonymous> (src/actions/tests/ast.spec.js:198:23)
          at Generator.next (<anonymous>)
      at step (src/actions/tests/ast.spec.js:18:397)
      at src/actions/tests/ast.spec.js:18:557
          at <anonymous>
```

**Comment by lukaszsobek** [comment]
Is fixed: 
![cannot-unfocus-prettyprint](https://user-images.githubusercontent.com/23530054/33599438-768612a0-d9a6-11e7-944d-eded828c37ec.gif)
