### ISSUE TITLE
npm install throws ENOENT: no such file or directory, chmod debugger.html/node_modules/devtools-mc-assets/sync.js

### ISSUE THREAD

**Issue by imvetri** [devtools-html/debugger.html#4748]
I cloned the repo recently and tried running npm install. I am getting below error.

![screen shot 2017-11-20 at 8 05 54 pm](https://user-images.githubusercontent.com/6542274/33024649-ade3f814-ce31-11e7-8f70-1009ab38a41c.png)

System details
Mac OS - Sierra
Node - v8.8.1
npm - v5.5.1

Just to cross check whether there could be problem in my environment, I tried cloning express and ran npm install on it. It went through without error.

**Comment by jasonLaster** [comment]
Hey @imvetri, i haven't seen that before. 

try running `yarn nom` happy to jump on a call too

**Comment by imvetri** [comment]
cool. no issues . now. thank you

**Comment by jasonLaster** [comment]
Thanks for sharing. It's good to be on the look out for that

**Comment by japrogramer** [comment]
Hello I have this issue too, why does this not work with npm?

**Comment by jasonLaster** [comment]
hi @japrogramer not sure... just published a new version. let me bump it in the debugger so it is used

**Comment by japrogramer** [comment]
well I managed to install with yarn, but i cant run 
~/git/debugger.html  master ✗                                                                                                                                                                                                                                                                                                                                                                                                  2h44m ⚑  ⍉
```
▶ yarn start
yarn run v1.3.2
warning You are using Node "7.10.1" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
$ node bin/dev-server
Listening for WS on localhost:8116, all traffic is proxied to localhost:6080
Protocol messages can be logged by enabling logging.firefoxProtocol in your local.json config
Hot Reloading - https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#hot-reloading
View debugger examples here:
https://github.com/devtools-html/debugger-examples
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8000
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at doListen (net.js:1432:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
about to pull latest code tho

**Comment by jasonLaster** [comment]
okay. two tips, upgrade node, downgrade yarn to 0.28.4

**Comment by japrogramer** [comment]
oh, ok. I was in nvm and didn't noticed i was using that node

**Comment by japrogramer** [comment]
Im using carbon with the recommended yarn version and Im still getting an error.
```
~/git/debugger.html  master ✗                                                                                                                                                                                                                                                                                                                                                                                                  2h56m ⚑  ⍉
▶ yarn nom
yarn nom v0.28.4
$ node bin/nom
Deleting node_modules and yarn.lock
Reinstalling packages
warning devtools-launchpad > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning devtools-launchpad > geckodriver > tar.gz@1.0.5: ⚠  WARNING ⚠ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
warning devtools-splitter > @percy-io/react-percy-storybook@0.1.12: WARNING: This module has been renamed. Please install @percy-io/percy-storybook instead. See https://github.com/percy/percy-storybook for more information.
warning @percy-io/react-percy-storybook@1.1.5: WARNING: This module has been renamed. Please install @percy-io/percy-storybook instead. See https://github.com/percy/percy-storybook for more information.
warning fsevents@1.1.3: The platform "linux" is incompatible with this module.
warning "babel-loader@7.1.2" has incorrect peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning "react-redux@5.0.6" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
warning "react-immutable-proptypes@2.1.0" has incorrect peer dependency "immutable@>=3.6.2".
warning "url-loader@0.5.9" has incorrect peer dependency "file-loader@*".
warning "ajv-keywords@2.1.1" has incorrect peer dependency "ajv@^5.0.0".
warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
warning "request-promise@4.2.2" has incorrect peer dependency "request@^2.34".
warning "bluebird-retry@0.11.0" has incorrect peer dependency "bluebird@>=2.3.10".
warning "request-promise-core@1.1.1" has incorrect peer dependency "request@^2.34".
warning "react-inlinesvg@0.6.2" has incorrect peer dependency "prop-types@^15.5".
warning "url-loader@0.6.2" has incorrect peer dependency "file-loader@*".
warning "babel-preset-react-app@3.1.0" has incorrect peer dependency "babel-runtime@^6.23.0".
package.json 51ms
Done in 36.96s.

~/git/debugger.html  master ✗                                                                                                                                                                                                                                                                                                                                                                                                   2h56m ⚑
▶ yarn start
yarn start v0.28.4
$ node bin/dev-server
Listening for WS on localhost:8116, all traffic is proxied to localhost:6080
Protocol messages can be logged by enabling logging.firefoxProtocol in your local.json config
Hot Reloading - https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#hot-reloading
View debugger examples here:
https://github.com/devtools-html/debugger-examples
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.

~/git/debugger.html  master ✗                                                                                                                                                                                                                                                                                                                                                                                                  2h56m ⚑  ⍉
▶ npm ls -gp --depth=0
/home/archangel/.nvm/versions/node/v8.9.1/lib
/home/archangel/.nvm/versions/node/v8.9.1/lib/node_modules/npm
/home/archangel/.nvm/versions/node/v8.9.1/lib/node_modules/yarn

~/git/debugger.html  master ✗                                                                                                                                                                                                                                                                                                                                                                                                   2h57m ⚑
▶ yarn version
yarn version v0.28.4
info Current version: 0.6.0
question New version: %

~/git/debugger.html  master ✗
```

**Comment by jasonLaster** [comment]
try, restarting your computer to drop the running server. also, make sure debugger.html master is up to date

**Comment by japrogramer** [comment]
good idea, I had a docker instance listening on port 8000, is there a way to specify the port I want debugger.html to run in?
