### ISSUE TITLE
Source Maps - investigate failing tests

### ISSUE THREAD

**Issue by jasonLaster** [devtools-html/debugger.html#492]
It looks like the source map tests are failing too regularly

Here's a good example run
https://circleci.com/gh/jasonLaster/debugger.html/726

It looks like there's an interesting pattern here where the first and second failures are similar across runs, not sure if it's a coincidence.

**first run**
```
  1) Todo MVC (Chrome) Source Maps:
     Uncaught Error: Uncaught TypeError: Cannot read property 'toJS' of undefined (http://localhost:2020/public/build/bundle.js:67954)
      at uncaughtException.n.onerror (http://localhost:2020/__cypress/static/js/vendor.js:33:12620)
      at window.onerror (http://localhost:2020/?chrome-tab=4c47face-efc1-4f4b-83a9-9da8c2f73520:3:86)
      at Object.$Cypress.Mouse.Promise.click (http://localhost:2020/__cypress/static/js/cypress.js:3495:40)
      at afterMouseDown (http://localhost:2020/__cypress/static/js/cypress.js:6304:55)
      at http://localhost:2020/__cypress/static/js/cypress.js:6492:32
      at i (http://localhost:2020/__cypress/static/js/vendor.js:582:27)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:581:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:581:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:581:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:580:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:580:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:580:1186)

```

**second run**
```
  1) Todo MVC (Chrome) Source Maps:
     CypressError: Timed out retrying: Expected to find content: '3' within the element: <div.CodeMirror.cm-s-default> and with the selector: '.CodeMirror-linenumber' but never did.
      at Object.$Cypress.Utils._.cypressErr (http://localhost:2020/__cypress/static/js/cypress.js:4758:15)
      at Object.$Cypress.Utils._.throwErr (http://localhost:2020/__cypress/static/js/cypress.js:4722:22)
      at Object.$Cypress.Utils._.throwErrByPath (http://localhost:2020/__cypress/static/js/cypress.js:4750:21)
      at $Cypress.Cy.extend._retry (http://localhost:2020/__cypress/static/js/cypress.js:5681:26)
      at http://localhost:2020/__cypress/static/js/cypress.js:7713:28
      at i (http://localhost:2020/__cypress/static/js/vendor.js:582:27)
      at e._settlePromiseFromHandler (http://localhost:2020/__cypress/static/js/vendor.js:581:5260)
      at e._settlePromiseAt (http://localhost:2020/__cypress/static/js/vendor.js:581:6529)
      at e._settlePromises (http://localhost:2020/__cypress/static/js/vendor.js:581:8394)
      at i._drainQueue (http://localhost:2020/__cypress/static/js/vendor.js:580:3183)
      at i._drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:580:3244)
      at MutationObserver.drainQueues (http://localhost:2020/__cypress/static/js/vendor.js:580:1186)
```

**Comment by jasonLaster** [comment]
I believe these failures were fixed by  these two commits [1](https://github.com/devtools-html/debugger.html/tree/b3ce17ca6cc928a79c0ec6bb9bbb860fd70141c1), [2](https://github.com/devtools-html/debugger.html/tree/81b92e1c8b06f03e4b9c408d050c34146167a34b).
