### ISSUE TITLE
`yarn copy` error when `firefox` directory not present

### ISSUE THREAD

**Issue by darkwing** [devtools-html/debugger.html#6629]
I `rm -rf firefox` to get a fresh checkout of for building and testing.  Next I `yarn copy` and receive the following:

```shell
$ yarn copy
yarn run v1.6.0
(node:54036) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ node bin/copy --assets
Copying Files to ./firefox with params:  { watch: false, assets: true, symlink: false }
[copy-assets] start
[copy-assets] copy static assets:
[copy-assets] - properties
[copy-assets] - preferences
[copy-assets] - index.html, index.js
[copy-assets] - moz.build
[copy-assets] - dist/moz.build
[copy-assets] copy SVGs
(node:54037) ExperimentalWarning: The fs.promises API is experimental
(node:54037) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/davidwalsh/Projects/debugger.html/firefox/devtools/client/jar.mn'
    at Object.fs.openSync (fs.js:559:3)
    at Object.fs.readFileSync (fs.js:465:33)
    at updateFile (/Users/davidwalsh/Projects/debugger.html/bin/copy-assets.js:28:17)
    at copySVGs (/Users/davidwalsh/Projects/debugger.html/bin/copy-assets.js:101:3)
    at start (/Users/davidwalsh/Projects/debugger.html/bin/copy-assets.js:224:3)
    at module.exports (/Users/davidwalsh/Projects/debugger.html/bin/copy-assets.js:311:12)
    at start (/Users/davidwalsh/Projects/debugger.html/bin/copy.js:19:9)
    at Object.<anonymous> (/Users/davidwalsh/Projects/debugger.html/bin/copy.js:23:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
(node:54037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54037) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 2.93s.
```

It appears we're relying on a file we obviously don't have.

**Comment by darkwing** [comment]
Going to close this; I should manually run `./bin/download-firefox-artifact` first.
