### ISSUE TITLE
TypeError: source is undefined

### ISSUE THREAD

**Issue by janodvarko** [devtools-html/debugger.html#6786]
One of the top error appearing in Sentry (>20 times a day, Nightly) is:

```
TypeError: source is undefined
  at loadSourceText/<(resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/content/actions/sources.js:172:34)
  at thunk/</<(resource://devtools/shared/base-loader.js -> resource://devtools/client/shared/redux/middleware/thunk.js:15:9)
  at task/</<(resource://devtools/shared/base-loader.js -> resource://devtools/client/shared/redux/middleware/task.js:36:12)
  at dispatch(resource://devtools/shared/base-loader.js -> resource://devtools/client/shared/vendor/redux.js:755:18)
  at selectSource/<(resource://devtools/shared/base-loader.js -> resource://devtools/client/debugger/content/actions/sources.js:55:5)
  at thunk/</<(resource://devtools/shared/base-loader.js -> resource://devtools/client/shared/redux/middleware/thunk.js:15:9)
  at task/</<(resource://devtools/shared/base-loader.js -> resource://devtools/client/shared/redux/middleware/task.js:36:12)
  at setEditorLocation(chrome://devtools/content/debugger/debugger-view.js:620:5)
  at selectFrame(chrome://devtools/content/debugger/debugger-controller.js:892:7)
  at _onSelect(chrome://devtools/content/debugger/views/stack-frames-view.js:245:7)
  at _onSelect(self-hosted:987:17)
  at dispatchEvent(resource://devtools/shared/base-loader.js -> resource://devtools/client/shared/widgets/view-helpers.js:118:12)
  at set selectedItem(resource://devtools/shared/base-loader.js -> resource://devtools/client/shared/widgets/view-helpers.js:964:7)
  at set selectedDepth(chrome://devtools/content/debugger/views/stack-frames-view.js:150:5)
  at _refillFrames(chrome://devtools/content/debugger/debugger-controller.js:788:46)
  at StackFrames.prototype._onFrames<(chrome://devtools/content/debugger/debugger-controller.js:765:5)
  at InterpretGeneratorResume(self-hosted:1269:8)
  at next(self-hosted:1224:9)
  at _run(resource://devtools/shared/base-loader.js -> resource://devtools/shared/task.js:310:41)
  at _run(self-hosted:1031:17)
  at process(resource://gre/modules/Promise-backend.js:928:23)
  at walkerLoop(resource://gre/modules/Promise-backend.js:812:7)
  at walkerLoop(self-hosted:985:17)
  at walkerLoop(self-hosted:985:17)
  at scheduleWalkerLoop/<(resource://gre/modules/Promise-backend.js:748:11)
```

https://sentry.prod.mozaws.net/operations/nightly-js-errors/issues/4527417/

Sentry doesn't provide STR, but this might be good test whether/how the service is useful for increasing stability & quality.

Is this known issue?

Honza

**Comment by jasonLaster** [comment]
The stack trace shows that the error is for the old debugger
